In [17]:
import pandas as pd
from datetime import datetime, date, timedelta

In [18]:
# get the date of yesterday and convert it to the m-d-Y format
yesterday = (date.today() + timedelta(days = -1)).strftime("%m-%d-%Y")

In [19]:
#the url of global daily reports provided by Johns Hopkins University 
address = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/"
url = address + yesterday + ".csv"

In [21]:
# # load the csv data into pandas.DataFrame
# p_td = pd.read_csv(url)
# # Only show the data about Australia  
# data_td = p_td[p_td['Country_Region'] == 'Australia']
# data_td = data_td.drop(["FIPS", "Admin2"], axis=1)
# data_td = data_td.reset_index(drop=True)

In [44]:
data_td = pd.read_csv('04-25-2020.csv')

In [45]:
data_td.drop(columns=['Combined_Key'], inplace=True)

In [46]:
data_td['Population'] = [412576, 7544000, 211945, 5071000, 1677000, 515000, 6359000, 2589000]

In [47]:
data_td = data_td.astype({'Last_Update': 'datetime64'})

In [49]:
data_td['Death Rate'] = data_td['Deaths'] / data_td['Confirmed']
data_td['Confirmed/100k'] = ((data_td['Confirmed'] / data_td['Population'])*100000).round()

In [54]:
data_td.drop(columns = 'Population', inplace=True)
data_td = data_td[['Province_State', 'Country_Region','Active', 'Confirmed', 'Recovered','Deaths','Death Rate', 'Confirmed/100k','Last_Update', 'Lat', 'Long_']]

In [55]:
data_td

,Province_State,Country_Region,Active,Confirmed,Recovered,Deaths,Death Rate,Confirmed/100k,Last_Update,Lat,Long_
0,Australian Capital Territory,Australia,5,106,98,3,0.028302,26.0,2020-04-26 02:31:00,-35.4735,149.0124
1,New South Wales,Australia,768,2994,2193,33,0.011022,40.0,2020-04-26 02:31:00,-33.8688,151.2093
2,Northern Territory,Australia,28,28,0,0,0.000000,13.0,2020-04-26 02:31:00,-12.4634,130.8456
3,Queensland,Australia,217,1026,803,6,0.005848,20.0,2020-04-26 02:31:00,-27.4698,153.0251
4,South Australia,Australia,33,438,401,4,0.009132,26.0,2020-04-26 02:31:00,-34.9285,138.6007
5,Tasmania,Australia,80,207,117,10,0.048309,40.0,2020-04-26 02:31:00,-42.8821,147.3272
6,Victoria,Australia,1197,1346,133,16,0.011887,21.0,2020-04-26 02:31:00,-37.8136,144.9631
7,Western Australia,Australia,63,549,478,8,0.014572,21.0,2020-04-26 02:31:00,-31.9505,115.8605

In [7]:
data_td.to_csv(yesterday+'.csv', index=False)

In [8]:
# url of the time series data of global confirmed cases
url_hc= "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
# url of the time series data of global death cases
url_hd= "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
# url of the time series data of global recovered cases
url_hr= "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

In [9]:
p_hc = pd.read_csv(url_hc)
p_hd = pd.read_csv(url_hd)
p_hr = pd.read_csv(url_hr)

In [11]:
# Time series data of Australia confirmd cases
data_hc = p_hc[p_hc['Country/Region'] == 'Australia']
data_hc = data_hc.reset_index(drop=True)
data_hc

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,4/21/20,4/22/20,4/23/20,4/24/20,4/25/20
0,Australian Capital Territory,Australia,-35.4735,149.0124,0,0,0,0,0,0,...,103,103,103,103,104,104,104,104,105,106
1,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,3,4,...,2897,2926,2936,2957,2963,2969,2971,2976,2982,2994
2,Northern Territory,Australia,-12.4634,130.8456,0,0,0,0,0,0,...,28,28,28,28,28,28,28,28,28,28
3,Queensland,Australia,-28.0167,153.4000,0,0,0,0,0,0,...,1001,1007,1015,1019,1019,1024,1024,1026,1026,1026
4,South Australia,Australia,-34.9285,138.6007,0,0,0,0,0,0,...,433,435,435,435,435,437,438,438,438,438
5,Tasmania,Australia,-41.4545,145.9707,0,0,0,0,0,0,...,169,180,188,195,200,201,205,207,207,207
6,Victoria,Australia,-37.8136,144.9631,0,0,0,0,1,1,...,1299,1302,1319,1328,1329,1336,1336,1337,1343,1346
7,Western Australia,Australia,-31.9505,115.8605,0,0,0,0,0,0,...,532,541,544,545,545,546,546,546,548,549

In [17]:
data_hc  = data_hc.drop(columns = ['Country/Region', 'Lat', 'Long'])

In [44]:
df0 = pd.DataFrame(data_hc.stack()[0], columns= ['Australian Capital Territory']).drop('Province/State')
df1 = pd.DataFrame(data_hc.stack()[1], columns= ['NSW']).drop('Province/State')
df2 = pd.DataFrame(data_hc.stack()[2], columns= ['Northern Territory']).drop('Province/State')
df3 = pd.DataFrame(data_hc.stack()[3], columns= ['Queensland']).drop('Province/State')
df4 = pd.DataFrame(data_hc.stack()[4], columns= ['South Australia']).drop('Province/State')
df5 = pd.DataFrame(data_hc.stack()[5], columns= ['Tasmania']).drop('Province/State')
df6 = pd.DataFrame(data_hc.stack()[6], columns= ['Victoria']).drop('Province/State')
df7 = pd.DataFrame(data_hc.stack()[7], columns= ['Western Australia']).drop('Province/State')

In [64]:
df_confirmed = pd.concat([df0, df1, df2, df3, df4, df5, df6, df7], axis =1)

In [88]:
list1 = []
list2 = []
for i in range(len(df_confirmed)):
     list1.append(df_confirmed.index[i]) 
     list2.append(df_confirmed.iloc[i].sum())

In [94]:
df_confirmed = pd.DataFrame({'Date':list1, 'Total':list2})
df_confirmed.to_csv('confirmed.csv',index=False)

In [99]:
# Time series data of Australia Deaths
data_hd = p_hd[p_hd['Country/Region'] == 'Australia']
data_hd = data_hd.reset_index(drop=True)

In [100]:
data_hd  = data_hd.drop(columns = ['Country/Region', 'Lat', 'Long'])

In [102]:
df0 = pd.DataFrame(data_hd.stack()[0], columns= ['Australian Capital Territory']).drop('Province/State')
df1 = pd.DataFrame(data_hd.stack()[1], columns= ['NSW']).drop('Province/State')
df2 = pd.DataFrame(data_hd.stack()[2], columns= ['Northern Territory']).drop('Province/State')
df3 = pd.DataFrame(data_hd.stack()[3], columns= ['Queensland']).drop('Province/State')
df4 = pd.DataFrame(data_hd.stack()[4], columns= ['South Australia']).drop('Province/State')
df5 = pd.DataFrame(data_hd.stack()[5], columns= ['Tasmania']).drop('Province/State')
df6 = pd.DataFrame(data_hd.stack()[6], columns= ['Victoria']).drop('Province/State')
df7 = pd.DataFrame(data_hd.stack()[7], columns= ['Western Australia']).drop('Province/State')
df_death = pd.concat([df0, df1, df2, df3, df4, df5, df6, df7], axis =1)
list1 = []
list2 = []
for i in range(len(df_death)):
     list1.append(df_death.index[i]) 
     list2.append(df_death.iloc[i].sum())
df_death = pd.DataFrame({'Date':list1, 'Total':list2})
df_death.to_csv('death.csv',index=False)

In [103]:
# Times series data of Australia recovered cases
data_hr = p_hr[p_hr['Country/Region'] == 'Australia']
data_hr = data_hr.reset_index(drop=True)
data_hr  = data_hr.drop(columns = ['Country/Region', 'Lat', 'Long'])

In [104]:
df0 = pd.DataFrame(data_hr.stack()[0], columns= ['Australian Capital Territory']).drop('Province/State')
df1 = pd.DataFrame(data_hr.stack()[1], columns= ['NSW']).drop('Province/State')
df2 = pd.DataFrame(data_hr.stack()[2], columns= ['Northern Territory']).drop('Province/State')
df3 = pd.DataFrame(data_hr.stack()[3], columns= ['Queensland']).drop('Province/State')
df4 = pd.DataFrame(data_hr.stack()[4], columns= ['South Australia']).drop('Province/State')
df5 = pd.DataFrame(data_hr.stack()[5], columns= ['Tasmania']).drop('Province/State')
df6 = pd.DataFrame(data_hr.stack()[6], columns= ['Victoria']).drop('Province/State')
df7 = pd.DataFrame(data_hr.stack()[7], columns= ['Western Australia']).drop('Province/State')
df_recovered = pd.concat([df0, df1, df2, df3, df4, df5, df6, df7], axis =1)
list1 = []
list2 = []
for i in range(len(df_recovered)):
     list1.append(df_recovered.index[i]) 
     list2.append(df_recovered.iloc[i].sum())
df_recovered = pd.DataFrame({'Date':list1, 'Total':list2})
df_recovered.to_csv('recovered.csv',index=False)